const datagalaxia = [
    {
        id:0,
        name: 'Salud Social',
        planetas: [
            {
                id: 1,
                name: 'Planeta COMPANIO',
                texture: '/assets/2k_makemake_fictional.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta COMPANIO\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Asociales-Hikikomori\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Solitarius',
                planetUrl: '/ninos/salud_social/planeta_comp',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 2,
                name: 'Planeta COMMUNIS',
                texture: '/assets/2k_haumea_fictional.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta COMMUNIS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Habilidades Comunicativas\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Distorsionarus',
                planetUrl: '/ninos/salud_social/planeta_com',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 3,
                name: 'Planeta EMOTIO',
                texture: '/assets/earthx5400x2700.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta EMOTIO\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Habilidades Emocionales\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Alterius',
                planetUrl: '/ninos/salud_social/planeta_emo',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 4,
                name: 'Planeta AMORE',
                texture: '/assets/2k_neptune.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta AMORE\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Habilidades Relacionales Nov.\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Manipularus',
                planetUrl: '/ninos/salud_social/planeta_amo',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 5,
                name: 'Planeta SEXUS',
                texture: '/assets/2k_venus_surface.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta SEXUS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Sexualidad D.\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Asexualis',
                planetUrl: '/ninos/salud_social/planeta_sexu',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 6,
                name: 'Planeta FORS',
                texture: '/assets/2k_uranus.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta FORS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Amistades-Influencias\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Perderius',
                planetUrl: '/ninos/salud_social/planeta_for',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 7,
                name: 'Planeta UTILIS',
                texture: '/assets/2k_venus_atmosphere.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta UTILIS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Habilidades Domesticas\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Inutileus',
                planetUrl: '/ninos/salud_social/planeta_util',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 8,
                name: 'Planeta PROPIUS',
                texture: '/assets/2k_earth_clouds.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta PROPIUS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Influenciadores\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Mangoneus',
                planetUrl: '/ninos/salud_social/planeta_pro',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 9,
                name: 'Planeta SENSUS',
                texture: '/assets/2k_jupiter.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta SENSUS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Ciencias de la tierra\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Insensiblus',
                planetUrl: '/ninos/salud_social/planeta_sen',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 10,
                name: 'Planeta DIRECTUS',
                texture: '/assets/2k_mars.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta DIRECTUS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Derechos digitales\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Desfavorecius',
                planetUrl: '/ninos/salud_social/planeta_dir',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 11,
                name: 'Planeta KRITIKOS',
                texture: '/assets/textura blanco.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta KRITIKOS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Nega y afirPeteicones\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Facilismus',
                planetUrl: '/ninos/salud_social/planeta_kri',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 12,
                name: 'Planeta MOYSIKO',
                texture: '/assets/textura negro.jpg',
                text: 'Tipo de riesgo: Salud Social\nPlaneta: Planeta MOYSIKO\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Música addictive\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Extasius',
                planetUrl: '/ninos/salud_social/planeta_moy',
                activo: true,
                categoria: 'niños',
            }
        ]
    },
    {
        id: 1,
        name: 'Salud Física',
        planetas: [
            {
                id: 1,
                name: 'Planeta MANUS',
                texture: '/assets/2k_makemake_fictional.jpg',
                text: 'Tipo de riesgo: Salud Física\nPlaneta: Planeta MANUS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Whatsapitis\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Tendinitius',
                planetUrl: '/ninos/salud_fisica/planeta_man',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 2,
                name: 'Planeta LEVIS',
                texture: '/assets/2k_haumea_fictional.jpg',
                text: 'Tipo de riesgo: Salud Física\nPlaneta: Planeta LEVIS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Sedentarismo Digital\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Sinsalus',
                planetUrl: '/ninos/salud_fisica/planeta_lev',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 3,
                name: 'Planeta VERTERE',
                texture: '/assets/earthx5400x2700.jpg',
                text: 'Tipo de riesgo: Salud Física\nPlaneta: Planeta VERTERE\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Espolón Óseo- Síndrome de CUSHING \nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Jorobus- Lumbarus',
                planetUrl: '/ninos/salud_fisica/planeta_ver',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 4,
                name: 'Planeta BIOS',
                texture: '/assets/2k_neptune.jpg',
                text: 'Tipo de riesgo: Salud Física\nPlaneta: Planeta BIOS\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Cáncer de Tiroides\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Cancerus',
                planetUrl: '/ninos/salud_fisica/planeta_bio',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 5,
                name: 'Planeta ADDORMISC',
                texture: '/assets/2k_venus_surface.jpg',
                text: 'Tipo de riesgo: Salud Física\nPlaneta: Planeta ADDORMISC\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Síndrome de la Pantalla Azul- Sequedad Ocular\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Invidentius',
                planetUrl: '/ninos/salud_fisica/planeta_add',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 6,
                name: 'Planeta ELEKTRON',
                texture: '/assets/2k_uranus.jpg',
                text: 'Tipo de riesgo: Salud Física\nPlaneta: Planeta ELEKTRON\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Exposición Electromagnética\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Radioactivus',
                planetUrl: '/ninos/salud_fisica/planeta_ele',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 7,
                name: 'Planeta MELIOR',
                texture: '/assets/2k_venus_atmosphere.jpg',
                text: 'Tipo de riesgo: Salud Física\nPlaneta: Planeta MELIOR\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Enfermedades Gastrointestinales\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Microbiotus',
                planetUrl: '/ninos/salud_fisica/planeta_mel',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 8,
                name: 'Planeta AUDITIO',
                texture: '/assets/2k_earth_clouds.jpg',
                text: 'Tipo de riesgo: Salud Física\nPlaneta: Planeta AUDITIO\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Hipoacusia o Total Cofosis- Sordera\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Sorderus',
                planetUrl: '/ninos/salud_fisica/planeta_aud',
                activo: true,
                categoria: 'niños',
            }
        ]
    },
    {
        id: 2,
        name: 'Salud Mental',
        planetas: [
            {
                id: 1,
                name: 'Planeta CONSCIRE',
                texture: '/assets/2k_makemake_fictional.jpg',
                text: 'Tipo de riesgo: Salud Mental\nPlaneta: Planeta CONSCIRE\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Realidad virtual\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Artificialis',
                planetUrl: '/ninos/salud_mental/planeta_cons',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 2,
                name: 'Planeta IMAGINATIO',
                texture: '/assets/2k_haumea_fictional.jpg',
                text: 'Tipo de riesgo: Salud Mental\nPlaneta: Planeta IMAGINATIO\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Cibercondria\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Dolientis',
                planetUrl: '/ninos/salud_mental/planeta_ima',
                activo: true,
                categoria: 'niños',
            }
        ]
    },
    {
        id: 3,
        name: 'Peligros Digitales',
        planetas: [
            {
                id: 1,
                name: 'Planeta KIO',
                texture: '/assets/2k_makemake_fictional.jpg',
                text: 'Tipo de riesgo: Peligros Digitales\nPlaneta: Planeta KIO\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Cyberbullying\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Artificialis',
                planetUrl: '/ninos/peligros_digitales/planeta_kio',
                activo: true,
                categoria: 'niños',
            },
            {
                id: 2,
                name: 'Planeta VÍTREO',
                texture: '/assets/2k_haumea_fictional.jpg',
                text: 'Tipo de riesgo: Peligros Digitales\nPlaneta: Planeta VÍTREO\nTamaño del planeta: 1.737,4 km\nComposición: Tierra árida\nNombre del riesgo: Grooming\nNivel de riesgo: Alto\nAmbiente: Tóxico\nTemperatura: -30°C a 127°C\nVillano: Pedofilus',
                planetUrl: '/ninos/peligros_digitales/planeta_2',
                activo: true,
                categoria: 'niños',
            }
        ]
    }
]

export default datagalaxia;
